refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
root:
  level: debug
  appenders:
    - stdout
loggers:
  decen_peer::file_check:
    level: debug
    appenders:
      - requests
      - stdout
    additive: false